AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  RiskIdent Backend

Parameters:
  ENVIRONMENT:
    Type: String
    Description: Environment name

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Runtime: nodejs12.x
    Timeout: 30
    MemorySize: 384
    Environment:
      Variables:
        ENVIRONMENT: !Ref ENVIRONMENT

Resources:
  GetTransactions:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: !Join [ "-", [ !Ref ENVIRONMENT, 'GetTransactions' ]]
      CodeUri: ../../build
      Handler: index.Handlers.getTransactions
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /transactions
            Method: get
            RequestParameters:
              - method.request.querystring.transactionId
              - method.request.querystring.confidenceLevel

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  GetTransactionsApi:
    Description: "API Gateway endpoint URL for Get Transactions function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/${ServerlessRestApiProdStage}/transactions?transactionId=5c868b22eb7069b50c6d2d32&confidenceLevel=0.9"
